### ISSUE TITLE
Property 'useReactNative' does not exist on type 'Reactotron'

### ISSUE THREAD

**Issue by derekstavis** [infinitered/reactotron-react-native#17] opened 2019-03-06 18:51 UTC
Following the getting started on React Native tutorial on a TypeScript project is giving me the error on the issue's title.

This is the snippet I'm using:

```tsx
import Reactotron from "reactotron-react-native";

Reactotron.configure()
  .useReactNative()
  .connect();
```

Versions:

`reactotron-react-native@3.2.1`
`typescript@3.3.3333`

**Comment by rmevans9** [comment] 2019-03-12 00:13
Hey @derekstavis!

Sorry for the delay in my response. I just installed `reactotron-react-native` in a test TypeScript project and it was able to find the definitions in 3.2.1. Can you please confirm a few things for me:

1. Can you open `reactotron-react-native` in your `node_modules` folder and screenshot the contents?
2. Can you tell me the version reported in the `package.json` file within `reactotron-react-native` in `node_modules`
3. Can you tell me if it knows the definition for `.configure()`
4. Can you tell me the version of `reactotron-core-client` that is installed?

**Comment by francisrod01** [comment] 2019-03-13 18:25
@rmevans9 here's a screenshot about `reactotron-react-native` content:

![image](https://user-images.githubusercontent.com/4691768/54304378-c9415a80-45a3-11e9-97c6-a9964f1b43c8.png)

Dependencies:

I'm using react-native ejected (without expo)  :100: 

- react@16.8.4
- react-native@0.59.0
- reactotron-react-native@3.2.1
- reactotron-redux@3.1.0

**Comment by francisrod01** [comment] 2019-03-13 22:31
I solved this problem installing `reactotron-react-native@3.2.1`. :+1:

**Comment by francisrod01** [comment] 2019-03-13 22:33
@derekstavis I solved this problem installing `react@16.6.1` and `react-native@0.57.7`.

**Comment by rmevans9** [comment] 2019-04-07 01:23
I am going to close this for now but if the issue persists please let me know

**Comment by pvinis** [comment] 2019-04-10 15:04
It is still like that. `useReactNative`, `clear`, `log`, `warn`, `error`, are all marked optional.
This is wrong. It comes from core-client, but the react-native one should make these non-optional.

**Comment by pvinis** [comment] 2019-04-10 15:05
Both on 3.2.1 and 3.2.2. It knows `configure`.

**Comment by pvinis** [comment] 2019-04-16 09:04
Can we reopen this?

**Comment by pvinis** [comment] 2019-04-16 09:05
`configure` returns `Reactotron`, and not `Reactotron & { useReactNative.. }`.

**Comment by rmevans9** [comment] 2019-04-16 09:16
Sure. I’ll take a look at this today.

**Comment by italomlp** [comment] 2019-05-02 00:19
+1 for this. Using React 16.8.3, React-Native 0.59.5, reactotron-react-native 3.3.0

**Comment by fbartho** [comment] 2019-05-08 22:28
I'm running into this issue as well.

The problem is the builder-pattern that's in use. The core `configure()` method needs to be generic on the type of Reactotron, that way the method signatures are available.

I was able to work around this by doing:

```typescript
	(Reactotron.configure({ name: "TR Client" }) as typeof Reactotron)
		.useReactNative(config)
		.connect();
```

**Comment by fbartho** [comment] 2019-05-08 23:33
I recommend that we make an interface in reactotron-core-client that generically defines the client in use.

Something like:

```typescript
export interface ReactotronCore {
	startTimer: () => () => number;
	close: () => void;
	send: (type: any, payload?: any, important?: boolean) => void;
	display: (config?: any) => void;
	reportError: (this: any, error: any) => void;
	onCustomCommand: (
		config: CustomCommandConfig | string,
		optHandler?: () => void,
	) => () => void;
	apiResponse?: (request: any, response: any, duration: any) => void;
	benchmark?: (
		title: string,
	) => {
		step: (stepName: string) => void;
		stop: (stopTitle: string) => void;
		last: (stopTitle: string) => void;
	};
	clear?: () => void;
	image?: (options: {
		uri: any;
		preview: any;
		filename: any;
		width: any;
		height: any;
		caption: any;
	}) => void;
	log?: (...args: any[]) => void;
	logImportant?: (...args: any[]) => void;
	debug?: (message: any, important?: boolean) => void;
	warn?: (message: any) => void;
	error?: (message: any, stack: any) => void;
	stateActionComplete?: (name: any, action: any, important?: boolean) => void;
	stateValuesResponse?: (path: any, value: any, valid?: boolean) => void;
	stateKeysResponse?: (path: any, keys: any, valid?: boolean) => void;
	stateValuesChange?: (changes: any) => void;
	stateBackupResponse?: (state: any) => void;
}

export interface Reactotron<ReactotronSubtype = ReactotronCore> {
	configure: (options?: ClientOptions) => Reactotron<ReactotronSubtype>;
	use: (
		pluginCreator?: (client: Reactotron<ReactotronSubtype>) => any,
	) => Reactotron<ReactotronSubtype>;
	connect: () => Reactotron<ReactotronSubtype>;
}
```

**Comment by italomlp** [comment] 2019-05-09 23:26
@fbartho your work around seems to good for now.

**Comment by rmevans9** [comment] 2019-05-17 02:07
@fbartho Would you mind putting up a PR with your suggested changes? I would gladly accept some help making the types better 👍

**Comment by fbartho** [comment] 2019-05-17 02:11
@rmevans9 I'm happy to open some PRs, but since it's changes across two repositories, do you have any concerns/suggestions on how I should go about this?

Fork both, open two linked PRs?

**Comment by rmevans9** [comment] 2019-05-17 02:19
Yeah, that works. You should be able to `(yarn/npm) link` between core-client and react-native to allow you to test them together before opening PRs.

**Comment by rmevans9** [comment] 2019-05-21 12:21
This should be resolved in the latest version

**Closed by rmevans9** 2019-05-21 12:21 UTC
Labels: help wanted

**Comment by derekstavis** [comment] 2019-05-22 00:42
I just noticed the activity on this one right now! Too many Github notifications! Thanks @fbartho!!
